<script>
  import Article from './components/Article.svelte';
  import Project from './components/Project.svelte';
  import Simulation from './components/Simulation.svelte';
  import { storable } from './js/storable.js'

  let activeSection = storable('activeSection', 'writing');
  let searchQuery = '';

  let articles = [
    {
      id: 0,
      href: "/articles/first-post",
      title: "First Post",
      date: "Dec 4, 2024",
      description: "My first post on this new version of my website."
    }
  ];

  let projects = [
    // {
    //   id: 0,
    //   href: "/",
    //   title: "DICE ROLLER",
    //   tags: "UI, TTRPG",
    //   description: "A simple but comprehensive dice roller to use for all of your tabletop role-playing needs!",
    //   img: ''
    // },
  ];

  let sims = [
    {
      id: 0,
      href: "/simulations/gol",
      title: "Conway's<br>Game of Life",
      imgPath: "/assets/images/sim1.png",
      imgDesc: "Black and white pixels on a grid, generated by Conway's Game of Life.",
      description: "A simple artificial life program."
    }
  ]

  let filteredArticles = articles;
  $: filteredArticles = articles.filter(item => item.title.toLowerCase().includes(searchQuery.toLowerCase()));
  let filteredProjects = projects;
  $: filteredProjects = projects.filter(item => item.title.toLowerCase().includes(searchQuery.toLowerCase()));
  let filteredSims = sims;
  $: filteredSims = sims.filter(item => item.title.toLowerCase().includes(searchQuery.toLowerCase()));

  function toggleShow(id) {
    activeSection.set(id);
  }

  import { onMount } from 'svelte';
  import { palette, switchPalette, setPalette, moonSVG, sunSVG } from './js/palette.js';

  onMount(() => {
    setPalette($palette);
  });
</script>

<div class="container">
  <header>
    <div class="home-header">
      <div class="logo-container">
        <button type="button" id="palette-button" aria-label="Switch Color Palette" on:click={switchPalette}>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -0.5 28 28" shape-rendering="crispEdges">
            <metadata>Made with Pixels to Svg https://codepen.io/shshaw/pen/XbxvNj</metadata>
            <path
              d="M9 0h9M7 1h13M5 2h4M11 2h11M4 3h4M9 3h2M12 3h4M19 3h4M3 4h1M5 4h11M20 4h4M2 5h1M4 5h2M7 5h11M20 5h1M23 5h2M1 6h1M3 6h23M3 7h2M6 7h2M10 7h7M18 7h8M0 8h1M5 8h3M10 8h2M15 8h3M19 8h1M22 8h5M4 9h2M7 9h4M16 9h2M19 9h1M23 9h4M5 10h5M12 10h3M16 10h5M23 10h5M2 11h3M6 11h4M11 11h4M16 11h12M5 12h1M7 12h3M11 12h4M16 12h12M6 13h6M15 13h13M7 14h5M14 14h2M18 14h10M1 15h1M7 15h9M18 15h10M1 16h2M7 16h3M13 16h5M20 16h5M26 16h2M2 17h2M7 17h2M10 17h3M14 17h4M20 17h1M23 17h5M6 18h4M13 18h1M15 18h6M23 18h1M26 18h1M0 19h1M4 19h5M14 19h1M17 19h6M25 19h2M1 20h1M6 20h2M17 20h6M24 20h2M6 21h2M15 21h4M20 21h2M24 21h2M7 22h1M9 22h2M16 22h5M24 22h1M3 23h1M10 23h3M23 23h1M4 24h1M18 24h2M17 25h1M10 27h1M12 27h1" />
          </svg>
        </button>
      </div>
      <div class="nav-container">
        <ul class="nav">
          <li>
            <button class="button-section" class:active={$activeSection === 'projects'} type="button" on:click={() => toggleShow('projects')}>projects</button>
          </li>
          <li>
            <button class="button-section" class:active={$activeSection === 'simulations'} type="button" on:click={() => toggleShow('simulations')}>simulations</button>
          </li>
          <li>
            <button class="button-section" class:active={$activeSection === 'writing'} type="button" on:click={() => toggleShow('writing')}>writing</button>
          </li>
          <li>
            <button class="button-section" class:active={$activeSection === 'all'} type="button" on:click={() => toggleShow('all')}>all</button>
          </li>
        </ul>
      </div>
        <div class="search-container">
          <input
            type="text"
            placeholder="Search {$activeSection}..."
            bind:value={searchQuery}
            aria-label="Search items"
          />
        </div>
    </div>
  </header>
  <main>
    <div class="octopus">a<br>a<br>a</div>
    <div class="main-content">
      <div class="column" id="column-left">
        <div class="intro" id="about">
          <div class="intro-title">
            <h2>ABOUT ME</h2>
          </div>
          <div class="intro-text">
            <p>Hi, I'm Chase. Mathematical biologist and creative technologist. <br>Currently at <a
                href="https://fathom.info" target="_blank">Fathom Information Design</a>. Previously at Harvard.</p>
            <br>
            <p><b>Interests</b>: Data visualization and modeling for social impact, evolutionary dynamics,
              computational theories of intelligence.</p>
            <br>
            <p><b>Goals</b>: Do something(s) interesting.</p>
          </div>
        </div>
      </div>
      <div class="column" id="column-right">
        <div class="projects" id="projects" class:hidden={$activeSection !== 'projects' && $activeSection !== 'all'}>
          <div class="projects-title">
            <h2>PROJECTS</h2>
            <p class="desc-text">Larger-scale work with tangible results and takeaways.</p>
          </div>
          <div class="project-grid">
            {#each filteredProjects as project}
              <Project
                id={project.id}
                title={project.title}
                href={project.href}
                tags={project.tags}
                description={project.description}
                img={project.img}
              />
            {/each}
          </div>
        </div>
        <div class="simulations" id="simulations" class:hidden={$activeSection !== 'simulations' && $activeSection !== 'all'}>
          <div class="sims-title">
            <h2>SIMULATIONS</h2>
            <p class="desc-text">Largely inspired by the sites of <a href="http://www.complexity-explorables.org"
                target="_blank">Dirk Brockmann</a> and <a href="http://ncase.me" target="_blank">Nicky Case</a>,
              these are interactive simulations for understanding cool natural phenomena.</p>
          </div>
          <div class="sim-list">
            {#each filteredSims as sim}
              <Simulation
                id={sim.id}
                title={sim.title}
                href={sim.href}
                imgPath={sim.imgPath}
                imgDesc={sim.imgDesc}
                description={sim.description}
              />
            {/each}
          </div>
        </div>
        <div class="articles" id="writing" class:hidden={$activeSection !== 'writing' && $activeSection !== 'all'}>
          <div class="articles-title">
            <h2>WRITING</h2>
            <p class="desc-text">A variety of musings and thoughts.</p>
          </div>
          <div class="article-list">
            {#each filteredArticles as article}
              <Article
                id={article.id}
                title={article.title}
                date={article.date}
                description={article.description}
                href={article.href}
              />
            {/each}
          </div>
        </div>
      </div>
    </div>
  </main>
  <footer>©2024 Chase Van Amburg</footer>
</div>